//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminParcial.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propietario()
        {
            this.Terrenoes = new HashSet<Terreno>();
        }
    
        public int Id_Propietario { get; set; }
        public string Nombre { get; set; }
        public string Apelllido { get; set; }
        public Nullable<int> DPI { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terreno> Terrenoes { get; set; }
    }
}
