//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminParcial.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public int Id_Recibo { get; set; }
        public Nullable<int> Id_Tereno { get; set; }
        public Nullable<int> Id_Pago_Detalle { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Mes { get; set; }
    
        public virtual Pago_Detalle Pago_Detalle { get; set; }
        public virtual Terreno Terreno { get; set; }
    }
}
