//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminParcial.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terreno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terreno()
        {
            this.Reciboes = new HashSet<Recibo>();
        }
    
        public int Id_Terreno { get; set; }
        public Nullable<int> Id_Propietario { get; set; }
        public string Lote { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Solvencia { get; set; }
    
        public virtual Propietario Propietario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibo> Reciboes { get; set; }
    }
}
